# https://hub.docker.com/r/library/node/tags/
image: node:lts

cache:
  paths:
    - backend/node_modules/

stages:
  - build
  - test
  - publish

build:
  only:
    - merge_requests
  stage: build
  script:
    - cd backend
    - yarn install

backend_prettier:
  only:
    - merge_requests
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn prettier:lint

backend_tsc:
  only:
    - merge_requests
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn tsc:lint

backend_eslint:
  only:
    - merge_requests
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn eslint:lint

backend_test:
  only:
    - merge_requests
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn test

# gitlab registry docs: https://docs.gitlab.com/12.10/ee/user/packages/npm_registry/index.html#authenticating-to-the-gitlab-npm-registry
publish_pre_release:
  stage: publish
  only:
    refs:
      - main
  script:
    - cd backend
    - npm set unsafe-perm true # https://docs.npmjs.com/cli/v6/using-npm/scripts#user
    - yarn
    - npm config set @tezos-kiln:registry https://gitlab.com/api/v4/projects/22897259/packages/npm/
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - npm config set '//gitlab.com/api/v4/projects/22897259/packages/npm/:_authToken' ${CI_JOB_TOKEN}
    - npm version prerelease -preid $(git rev-parse --short HEAD) -no-git-tag-version
    - npm publish --tag=dev

# https://docs.gitlab.com/ee/user/packages/container_registry/
dockerize_pre_release:
  stage: publish
  image: docker:latest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  services:
  - docker:dind
  only:
    refs:
      - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
