# https://hub.docker.com/r/library/node/tags/
image: node:latest

cache:
  paths:
    - backend/node_modules/

build:
  stage: build
  script:
    - cd backend
    - yarn install

backend_prettier:
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn prettier:lint

backend_tsc:
  stage: test
  dependencies: 
    - build
  script:
    - cd backend
    - yarn tsc:lint
